config/routes.rb
Rails.application.routes.draw do
  resources 'reservations'

  ActiveAdmin.routes(self)
  devise_for :users
  #root 'static_pages#index'
  root 'static_pages#index'
  # get 'contact', to: 'static_pages#contact'
  get 'commingsoon', to: 'static_pages#commingsoon'
  get 'newindex', to: 'static_pages#new_index'
  get 'menu', to: 'static_pages#menu'
  get '/robots.txt' => 'robots_txts#disallow_all'
end

app/views/layouts/_footer.html.slim
footer#footer.site-footer.candia-bg-overlay.candia-bg.bg-footer.text-center
  .container
    .candia-logo.mb-30
      a[href="index.html"]
        = image_tag 'IndianCafeDehliLogo.png'
    ul.nav.navbar-nav.main-navigation.color-white.mb-10
      li.dropdown
        = link_to 'Главная', root_path, class: 'dropdown-toggle'

      li.dropdown
        a.dropdown-toggle[href="#" data-toggle="dropdown"]
          | Бронирование

        /ul.dropdown-menu
        /  li
        /    a[href="reservation-1.html"]f
        /      | Book a table
        /  li
        /    a[href="reservation-2.html"]
        /      | Choose date
        /  li
        /    a[href="reservation-3.html"]
        /      | Confirmation
        /  li
        /    a[href="reservation-4.html"]
        /      | Completed
      li.dropdown
        a.dropdown-toggle[href="#" data-toggle="dropdown"]
          | Меню

        /ul.dropdown-menu
        /  li
        /    a[href="menu-parallax.html"]
        /      | Menu Parallax
        /  li
        /    a[href="menu-text.html"]
        /      | Menu Text
        /  li
        /    a[href="menu-zigzag.html"]
        /      | Menu ZigZag


      li.dropdown
        a.dropdown-toggle[href="#" data-toggle="dropdown"]
          | Блог
          b.caret
      li
        a[href="#"]
          | Contact

    nav.candia-social.color-white.text-center.mb-40
      a[href="https://www.facebook.com/Indian-Cafe-Delhi-1374553779266477" title="Facebook" target = "_blank"]
        i.fa.fa-facebook[aria-hidden="true"]
        span.sr-only
          | Facebook

      a[href="https://www.instagram.com/indiancafedelhi/" title="Instagram" target = "_blank"]
        i.fa.fa-instagram[aria-hidden="true"]
        span.sr-only
          | Instagram

    .color-white.fz-12
      p
        | © 2017 ИНДИЙСКИЙ КАФЕ ДЕЛИ
        | .
      #loader-wrapper
        .loader-section
        #loader
          label
            |  ●
          label
            |  ●
          label
            |  ●
          label
            |  ●
          label
            |  ●
          label
            |  ●

app/views/layouts/_header.slim
.site-header.site-header--transparent
  .container
    .site-header__content
      .center-height
        .center-height__item
          .candia-address
            p
              i.fa.fa-map-marker[aria-hidden="true"]
              |  м.Владимирская, ул.Разъезжая, д.7 📞 8(981)701-00-00
        .center-height__item
          .candia-logo.hidden-xs
            = image_tag 'IndianCafeDehliLogo.png'
          .candia-logo--small
            = image_tag 'IndianCafeDehliLogo.png'
        .center-height__item
          .candia-group.text-right
            nav.candia-social.hidden-sm
              a[href="https://www.facebook.com/Indian-Cafe-Delhi-1374553779266477" title="Facebook" target = "_blank"]
                i.fa.fa-facebook[aria-hidden="true"]
                span.sr-only
                  | Facebook
              a[href="https://www.instagram.com/indiancafedelhi/" title="Instagram" target = "_blank"]
                i.fa.fa-instagram[aria-hidden="true"]
                span.sr-only
                  | Instagram
              a[href="#" title="Tripadvisor"]
                i.fa.fa-tripadvisor[aria-hidden="true"]
                span.sr-only
                  | Tripadvisor
            .candia-dropdown.dropdown.text-uppercase
              a[data-target="#" href="#" data-toggle="dropdown" role="button"]
                | Ru
                i.fa.fa-chevron-down[aria-hidden="true"]
              ul.dropdown-menu
                li
                  a[href="#"]
                    | Eng
                li
                  a[href="#"]
                    | Ru
            .candia-dropdown.dropdown.text-uppercase
              a[data-target="#" href="#" data-toggle="dropdown" role="button"]
                | Руб
                i.fa.fa-chevron-down[aria-hidden="true"]
              ul.dropdown-menu
                li
                  a[href="#"]
                    | Руб
                li
                  a[href="#"]
                    | Usd
      nav.navbar.navbar-default.navbar-statis-top[role="navigation"]
        .navbar-header
          button.navbar-toggle[type="button" data-toggle="collapse" data-target="#main-navbar-collapse"]
            span.icon-bar
            span.icon-bar
            span.icon-bar
        .navbar-overlay
        #main-navbar-collapse.collapse.navbar-collapse
          button.navbar-toggle[type="button" data-toggle="collapse" data-target="#main-navbar-collapse"]
            span.icon-bar
            span.icon-bar
            span.icon-bar
          ul.nav.navbar-nav.main-navigation
            li
              = link_to 'Главная', root_path

            li
              a[href="#" data-toggle="dropdown"]
                | Бронирование

            li.dropdown
              a.dropdown-toggle[href="#" data-toggle="dropdown"]
                | Меню
                b.caret
              ul.dropdown-menu
                li
                  a[href=""]
                    | Бизнес ланч
                li = link_to 'Меню «Все дни»', menu_path

            li
              a[href="#" data-toggle="dropdown"]
                | Блог

            li
              a[href="#"]
                | Контакт

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = content_for?(:title) ? yield(:title) : 'ИНДИЙСКИЙ КАФЕ ДЕЛИ СПБ'
    meta name="description" content="#{yield_meta_tag(:description, 'IndianCafeDelhi Saint Petersburg')}"
    meta name="keywords" content="#{yield_meta_tag(:keywords, 'IndianCafeDelhi Saint Petersburg')}"
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

  body.mjpicker-color-candia
    = render 'toastr_rails/flash'
    = yield
    = render 'layouts/footer'
    
  

//javascript:
//  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
//  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
//  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
//  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
//
//  ga('create', 'UA-101658796-1', 'auto');
//  ga('send', 'pageview');